In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import f1_score
from sklearn.metrics import jaccard_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix

In [10]:
df=pd.read_csv('./train.csv')
df.info()
df.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
df_KNN = df.iloc[:, :10]
df_KNN['Sex'] = df_KNN.Sex.replace({'male': 0, 'female': 1})
df_KNN = df_KNN.sort_values(by='Age')
# df = df[df.line_race != 0]
# df.loc[df['column_name'] == some_value]
df_to_predict = df_KNN.loc[df_KNN['Age'].isna()]
df_KNN_train = df_KNN.loc[df_KNN['Age'].notna()]
df_KNN_train.head()

PassengerId  Survived  Pclass                             Name  Sex  \
803          804         1       3  Thomas, Master. Assad Alexander    0   
755          756         1       2        Hamalainen, Master. Viljo    0   
644          645         1       3           Baclini, Miss. Eugenie    1   
469          470         1       3    Baclini, Miss. Helene Barbara    1   
78            79         1       2    Caldwell, Master. Alden Gates    0   

      Age  SibSp  Parch  Ticket     Fare  
803  0.42      0      1    2625   8.5167  
755  0.67      1      1  250649  14.5000  
644  0.75      2      1    2666  19.2583  
469  0.75      2      1    2666  19.2583  
78   0.83      0      2  248738  29.0000

In [47]:
cols = ['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch']
X = df_KNN_train[cols].values
Y = df_KNN_train['Age'].values
X = X[7:,:]
Y = Y[7:]
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.8, random_state=73)
# print(X.shape)
# print(Y.shape)



In [51]:
x_real = df_to_predict[cols].values
x_real.shape

(177, 5)

In [69]:
from sklearn import svm

regr = svm.SVC()

regr.fit(X=x_train, y=y_train)


ValueError: Unknown label type: 'continuous'

In [31]:
preds = regr.predict(x_test)

In [32]:
regr.score(x_test,y_test)

0.23473166265724876

In [39]:
preds_int = np.array([int(x) for x in preds])
preds_int

array([34, 29, 18, 31, 19, 28, 19, 28, 34, 34, 34, 31, 24,  6, 31,  8, 18,
       34, 34, 27, 38, 31, 28, 39, 19, 19, 49,  7, 26, 34,  8, 32, 37, 34,
       49, 38, 28, 34, 30, 28, 27, 34, 34, 34, 28, 16, 39, 21, 49, 21, 34,
       25, 39,  6, 28, 34, 39, 31, 21, 14, 31,  7, 17,  6, 42,  6, 32, 31,
       14, 34, 34, 28, 26, 34, 34, 35, 38, 24, 38, 26, 38, 34, 34, 21, 42,
       21, 28, 42,  7, 22, 34, 31, 21, 33, 34, 28, 38, 34, 34, 34, 34,  6,
       34,  7, 30, 33, 23, 34, 24, 30, 34, 34, 31, 28,  4, 49, 34, 34,  8,
       38, 31, 34, 19,  6, 26,  6, 34, 34, 21, 28, 27, 34, 22, 30, 34, 34,
       24, 18, 33, 34, 22, 34])

In [34]:
y_test

array([24., 32., 45., 28., 18., 42., 22., 30., 49., 20., 32., 32., 32.,
        3., 30., 11., 24., 33., 39., 41., 35., 36., 46., 39.,  4., 18.,
       36.,  9., 18., 25.,  1., 44., 31., 59., 31., 28., 27., 47., 39.,
       39., 26., 28., 25., 29., 57.,  4., 39., 45., 29., 34., 21., 30.,
       38.,  2., 18., 19., 29., 24., 24.,  9., 45., 33., 24.,  9., 48.,
        5., 23., 36.,  3., 42., 40.,  2., 26., 29., 58., 28., 32., 24.,
       51., 20., 34., 42., 20.,  4., 25., 31., 24., 27.,  2.,  3., 33.,
       34., 37., 13., 25., 59., 28., 18., 28., 17., 28., 14., 54., 24.,
       52., 24., 40., 16., 28., 48., 21., 22., 42., 36.,  2., 47., 47.,
       50., 14., 52., 57., 38., 19.,  4., 47., 17., 18., 38., 45., 36.,
       58., 39., 24., 17., 32., 20., 19.,  2., 21., 18.,  2., 17.])

In [46]:
acc = sum(preds_int == y_test) / preds_int.shape[0]
acc

0.035211267605633804

In [49]:
preds_real = regr.predict(x_real)
preds_real

array([34. , 34.4, 19.6, 34. , 19.6, 34. , 30.8, 19.6, 29.6, 34. , 34. ,
       24.2, 19.6, 27.4, 38.2, 49.8, 14.2, 34. , 34. , 19.6, 34. , 34. ,
       34. , 29.6, 22.4, 34. , 34. , 19.6, 23.9, 34. , 34. ,  8. , 34.8,
       49.8,  4.2,  8.4, 28. , 49.8, 22.4, 34. , 19.6,  8. , 24.2, 34. ,
        4.8, 21.6, 26.3, 22.4, 34. , 34.4, 34. , 21.6, 49.8, 19.6, 28. ,
       49.8, 49.8, 38.2, 19.6, 24.4, 31.4, 34. , 34.4,  8. , 20.4, 30.8,
       34. , 22.4, 49.8, 34. , 19.6, 19.6, 24.2, 19.6, 19.6, 30.8, 34. ,
       34. ,  4.8, 34. , 34. , 28. , 21.6, 34. , 34. , 34. , 22.4, 29.6,
       24.2, 34. , 30.8, 34. , 34. , 28. , 34. , 34. , 49.8, 28. ,  4.8,
       24.2, 34. , 34. , 21.6, 38.2, 34. , 34. , 34. , 34. , 49.8, 34. ,
       17. , 34. , 34.4, 34. , 49.8, 34. , 34. , 21.6, 34. , 19.6, 26.3,
       34. , 34. , 23.9, 31.4, 34. , 34. , 49.8, 34. , 22.4, 34. , 34. ,
       49.8, 24.2, 29.6, 34. , 34. , 19.6, 34. , 34. , 30.8, 28. , 21.6,
       29.6, 19.6, 14.2, 49.8, 34. , 19.6, 28. , 34

In [50]:
preds_real.shape

(177,)

In [55]:
df_to_predict.shape

(177, 10)

In [59]:
df_to_predict.iloc['Age_pred'] = preds_real

ValueError: Must have equal len keys and value when setting with an iterable

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=91fc748d-6dfe-4653-b79b-4cbc51a66576' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>